name: trigger update

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
           
permissions: write-all
  
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Pull 
        run: |
          git config user.name ${{ github.actor }}
          git subtree pull --prefix limiter  https://github.com/liranpi2/limiter.git master && git merge -s ours --allow-unrelated-histories -m "msg"
          git push
        continue-on-error: true 
