name: trigger update

on:
  schedule:
    - cron:  '*/5 * * * *'
    
permissions: write-all
  
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Pull 
        run: |
          git config user.name ${{ github.actor }}
          git merge -s subtree -Xsubtree="$prefix" limiter/master --allow-unrelated-histories
          git push
        continue-on-error: true 
