name: trigger update

on:
  schedule:
    - cron:  '*/5 * * * *'
    
permissions: write-all
  
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Pull 
        run: |
          git subtree pull --prefix limiter https://github.com/liranpi2/limiter.git master
      - name: Commit & push changes
        run: |
          git config user.name ${{ github.actor }}
          git merge -s subtree -Xsubtree="$prefix" limiter/master --allow-unrelated-histories
          git commit -am "Auto updated references" && git push || echo "No changes to commit"
